name: circuit_recognition_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  file_picker: ^9.0.2
  image: ^3.0.2
  opencv_core: ^1.3.2
  meta: ^1.15.0
  ffi: ^2.1.0
  tuple: ^2.0.0
  quiver: ^3.0.1
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/Rocket.jpg
  - assets/images/Stars.jpg
  - assets/images/Sunset.jpg
  - assets/images/circuitTest1.jpg
  - assets/images/circuitTestExpected1.png
  - assets/models/yolo11.tflite
  - assets/models/yolo11NMS.tflite
  - assets/models/yolo11classes45.tflite
  - assets/models/yolo11NMSclasses45.tflite
  - assets/models/yolo12.tflite
  - assets/models/yolo9.tflite
  - assets/models/detect.tflite
  - assets/models/yolo9_float32.tflite
  - assets/labels/yolo9labels.txt