// electronic-circuits-ifz6c
// Handdrawn characters
List<String> labels = [
  'and', 'antenna', 'capacitor-polarized', 'capacitor-unpolarized', 'crossover', 'diac', 'diode', 'diode-light_emitting', 'fuse', 'gnd', 'inductor', 'integrated_circuit', 'integrated_cricuit-ne555', 'junction', 'lamp', 'microphone', 'motor', 'nand', 'nor', 'not', 'operational_amplifier', 'optocoupler', 'or', 'probe-current', 'relay', 'resistor', 'resistor-adjustable', 'resistor-photo', 'schmitt_trigger', 'socket', 'speaker', 'switch', 'terminal', 'text', 'thyristor', 'transformer', 'transistor', 'transistor-photo', 'triac', 'varistor', 'voltage-dc', 'voltage-dc_ac', 'voltage-dc_regulator', 'vss', 'xor'
];
// circuit-schematic-detection
// const List<String> labels = [
//   '7 segments',
//   'AC source', 
//   'AMPERIMETER', 
//   'Capacitor', 
//   'DC source', 
//   'V', 
//   'VARIABLE CAPACITOR', 
//   'VOLTIMETER', 
//   'Wattimeter', 
//   'amplifier', 
//   'and gate', 
//   'box', 
//   'diode', 
//   'heating element', 
//   'inductor', 
//   'led', 
//   'light', 
//   'magnetron', 
//   'microphone', 
//   'mosfet', 
//   'motor', 
//   'nand gate', 
//   'nor gate', 
//   'not gate', 
//   'ohmmeter', 
//   'operational amplifier', 
//   'or gate', 
//   'potentiometer', 
//   'resistor', 
//   'schottky-zener diode', 
//   'switch', 
//   'transformer', 
//   'transistor', 
//   'variable resistor', 
//   'xnor gate', 
//   'xor gate'
// ];
// Coco.yaml
// const List<String> labels = [
//   'Person',
//   'Bicycle',
//   'Car',
//   'Motorbike',
//   'Airplane',
//   'Bus',
//   'Train',
//   'Truck',
//   'Boat',
//   'Traffic light',
//   'Fire hydrant',
//   'Stop sign',
//   'Parking meter',
//   'Bench',
//   'Bird',
//   'Cat',
//   'Dog',
//   'Horse',
//   'Sheep',
//   'Cow',
//   'Elephant',
//   'Bear',
//   'Zebra',
//   'Giraffe',
//   'Backpack',
//   'Umbrella',
//   'Handbag',
//   'Tie',
//   'Suitcase',
//   'Frisbee',
//   'Skis',
//   'Snowboard',
//   'Sports ball',
//   'Kite',
//   'Baseball bat',
//   'Baseball glove',
//   'Skateboard',
//   'Surfboard',
//   'Tennis racket',
//   'Bottle',
//   'Wine glass',
//   'Cup',
//   'Fork',
//   'Knife',
//   'Spoon',
//   'Bowl',
//   'Banana',
//   'Apple',
//   'Sandwich',
//   'Orange',
//   'Broccoli',
//   'Carrot',
//   'Hot dog',
//   'Pizza',
//   'Donut',
//   'Cake',
//   'Chair',
//   'Sofa',
//   'Potted plant',
//   'Bed',
//   'Dining table',
//   'Toilet',
//   'Tv monitor',
//   'Laptop',
//   'Mouse',
//   'Remote',
//   'Keyboard',
//   'Cell phone',
//   'Microwave',
//   'Oven',
//   'Toaster',
//   'Sink',
//   'Refrigerator',
//   'Book',
//   'Clock',
//   'Vase',
//   'Scissors',
//   'Teddy bear',
//   'Hair drier',
//   'Toothbrush',
// ];
